"""initial migration

Revision ID: 7ca8a9ce566f
Revises:
Create Date: 2024-12-15 19:38:32.754187

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "7ca8a9ce566f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "duty_day",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("duty_date", sa.Date(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.Column("is_done", sa.Boolean(), nullable=False),
        sa.Column("photo_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("report_room_number", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("duty_date"),
    )
    op.create_table(
        "room",
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("floor", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("number"),
    )
    op.create_table(
        "duty_room",
        sa.Column("duty_day_id", sa.Integer(), nullable=False),
        sa.Column("room_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["duty_day_id"], ["duty_day.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["room_number"],
            ["room.number"],
        ),
        sa.PrimaryKeyConstraint("duty_day_id", "room_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("duty_room")
    op.drop_table("room")
    op.drop_table("duty_day")
    # ### end Alembic commands ###
